@ECHO OFF
SET CLAUDE_CODE_GIT_BASH_PATH=D:\Development\Git\bin\bash.exe
SET ANTHROPIC_BASE_URL=https://api.nextgen-beta.ica.ibm.com/ica
SET ANTHROPIC_API_KEY=dummy-key
SET ANTHROPIC_AUTH_TOKEN=sk-WVm0cS8mpXgqkIFYPQ_YTQ
SET ANTHROPIC_MODEL=claude-sonnet-5
SET ANTHROPIC_DEFAULT_OPUS_MODEL=claude-sonnet-5
SET ANTHROPIC_DEFAULT_SONNET_MODEL=claude-sonnet-4-6
SET ANTHROPIC_DEFAULT_HAIKU_MODEL=claude-haiku-4-5
SET CLAUDE_CODE_SUBAGENT_MODEL=claude-sonnet-4-6
SET CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS=1
SET CURRENTDIRECTORY=%~dp0
SET USERPROFILE=%CURRENTDIRECTORY%Users\Claude
SET APPDATA=%CURRENTDIRECTORY%Users\Claude\AppData\Roaming
SET LOCALAPPDATA=%CURRENTDIRECTORY%Users\Claude\AppData\Local
IF NOT EXIST "%APPDATA%" MKDIR "%APPDATA%" >NUL
IF NOT EXIST "%LOCALAPPDATA%" MKDIR "%LOCALAPPDATA%" >NUL

ECHO.
ECHO To launch Claude Code enter: Claude

