@ECHO OFF
SET CLAUDE_CODE_GIT_BASH_PATH=D:\Development\Git\bin\bash.exe
SET ANTHROPIC_API_KEY=dummy-key
SET ANTHROPIC_BASE_URL=http://localhost:8000
SET CURRENTDIRECTORY=%~dp0
SET USERPROFILE=%CURRENTDIRECTORY%Users\Claude
SET APPDATA=%CURRENTDIRECTORY%Users\Claude\AppData\Roaming
SET LOCALAPPDATA=%CURRENTDIRECTORY%Users\Claude\AppData\Local
IF NOT EXIST "%APPDATA%" MKDIR "%APPDATA%" >NUL
IF NOT EXIST "%LOCALAPPDATA%" MKDIR "%LOCALAPPDATA%" >NUL

ECHO.
ECHO To launch Claude Code enter: Claude

