@ECHO OFF
SET CURRENTDIRECTORY=%~dp0
SET USERPROFILE=%CURRENTDIRECTORY%Users\Bob
SET APPDATA=%CURRENTDIRECTORY%Users\Bob\AppData\Roaming
SET LOCALAPPDATA=%CURRENTDIRECTORY%Users\Bob\AppData\Local
SET PATH=%CURRENTDIRECTORY%users\Bob\AppData\Local\Programs\IBM Bob;%PATH%
IF NOT EXIST "%APPDATA%" MKDIR "%APPDATA%" >NUL
IF NOT EXIST "%LOCALAPPDATA%" MKDIR "%LOCALAPPDATA%" >NUL

ECHO.
ECHO To launch IBM Bob IDE enter: "BobIDE"
ECHO To launch IBM Bob Shell enter: "Bob"

