@ECHO OFF
SET CURRENTDIRECTORY=%~dp0
SET USERPROFILE=%CURRENTDIRECTORY%Users\Opencode
SET APPDATA=%CURRENTDIRECTORY%Users\Opencode\AppData\Roaming
IF NOT EXIST %APPDATA% MKDIR %APPDATA% >NUL

ECHO.
ECHO To launch Opencode enter: Opencode
