@ECHO OFF
SET CURRENTDIRECTORY=%~dp0
SET USERPROFILE=%CURRENTDIRECTORY%Users\Opencode
SET APPDATA=%CURRENTDIRECTORY%Users\Opencode\AppData\Roaming
SET LOCALAPPDATA=%CURRENTDIRECTORY%Users\Opencode\AppData\Local
IF NOT EXIST %APPDATA% MKDIR %APPDATA% >NUL
IF NOT EXIST "%LOCALAPPDATA%" MKDIR "%LOCALAPPDATA%" >NUL

ECHO.
ECHO To launch Opencode enter: Opencode
