@SET CURRENTDIRECTORY=%~dp0
@SET USERPROFILE=%CURRENTDIRECTORY%Users\LiteLLM
@SET APPDATA=%CURRENTDIRECTORY%Users\LiteLLM\AppData\Roaming
@IF NOT EXIST %APPDATA% MKDIR %APPDATA% >NUL

@SET LITELLM_PROXY_URL=http://localhost:4000
@SET LITELLM_PROXY_API_KEY=sk-1234
@SET LITELLM_SALT_KEY=sk-1234
@SET DATABASE_URL=postgres://postgres:trust@127.0.0.1:5432/litellm
@SET PORT=4000
@SET STORE_MODEL_IN_DB=True
