@ECHO OFF
SET CURRENTDIRECTORY=%~dp0
SET USERPROFILE=%CURRENTDIRECTORY%Users\Cursor
SET APPDATA=%CURRENTDIRECTORY%Users\Cursor\Appdata\Roaming
SET LOCALAPPDATA=%CURRENTDIRECTORY%Users\Cursor\AppData\Local
IF NOT EXIST "%CURRENTDIRECTORY%" MKDIR "%CURRENTDIRECTORY%" >NUL
IF NOT EXIST "%LOCALAPPDATA%" MKDIR "%LOCALAPPDATA%" >NUL

ECHO.
Start "Cursor" cmd.exe /K ".\Cursor\Cursor"
