@ECHO OFF
SET CURRENTDIR=%~dp0
SET USERPROFILE=%CURRENTDIR%Users\Cursor
SET APPDATA=%CURRENTDIR%Users\Cursor\Appdata\Roaming
SET LOCALAPPDATA=%CURRENTDIR%Users\Cursor\AppData\Local
IF NOT EXIST "%CURRENTDIR%" MKDIR "%CURRENTDIR%" >NUL
IF NOT EXIST "%LOCALAPPDATA%" MKDIR "%LOCALAPPDATA%" >NUL

ECHO.
Start "Cursor" cmd.exe /K ".\Cursor\Cursor"
