@ECHO OFF
SET CURRENTDIRECTORY=%~dp0
SET USERPROFILE=%CURRENTDIRECTORY%Users\N8n
SET APPDATA=%CURRENTDIRECTORY%Users\N8n\AppData\Roaming
SET LOCALAPPDATA=%CURRENTDIRECTORY%Users\N8n\AppData\Local
IF NOT EXIST "%APPDATA%" MKDIR "%APPDATA%" >NUL
IF NOT EXIST "%LOCALAPPDATA%" MKDIR "%LOCALAPPDATA%" >NUL

ECHO.
ECHO Activate N8N Python virtual environment: .venv\Scrips\activate
ECHO Start N8N by: npx n8n
