[project]
name = "litellm-proxy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "backoff>=2.2.1",
    "litellm[proxy]>=1.78.0",
    "prisma>=0.15.0",
]
