@ECHO OFF
SET CURRENTDIRECTORY=%~dp0
SET USERPROFILE=%CURRENTDIRECTORY%Users\Cline
SET APPDATA=%CURRENTDIRECTORY%Users\Cline\AppData\Roaming
SET LOCALAPPDATA=%CURRENTDIRECTORY%Users\Cline\AppData\Local
SET PATH=%USERPROFILE%\AppData\Local\Cline;%PATH%
IF NOT EXIST "%APPDATA%" MKDIR "%APPDATA%" >NUL
IF NOT EXIST "%LOCALAPPDATA%" MKDIR "%LOCALAPPDATA%" >NUL

IF NOT EXIST "%USERPROFILE%\.config" MKDIR "%USERPROFILE%\.config" >NUL
IF NOT EXIST "%USERPROFILE%\Documents" MKDIR "%USERPROFILE%\Documents" >NUL
IF NOT EXIST "%USERPROFILE%\Downloads" MKDIR "%USERPROFILE%\Downloads" >NUL


ECHO.
ECHO Start Cline IDE by: "Cline-App" .
