@ECHO OFF
SET CURRENTDIRECTORY=%~dp0
SET USERPROFILE=%CURRENTDIRECTORY%Users\LlxprtCli
SET APPDATA=%CURRENTDIRECTORY%Users\LlxprtCli\AppData\Roaming
SET LOCALAPPDATA=%CURRENTDIRECTORY%Users\LlxprtCli\AppData\Local
IF NOT EXIST "%APPDATA%" MKDIR "%APPDATA%" >NUL
IF NOT EXIST "%LOCALAPPDATA%" MKDIR "%LOCALAPPDATA%" >NUL

ECHO .
ECHO To launch Llxprt Cli enter: Llxprt
