@ECHO OFF
SET CURRENTDIRECTORY=%~dp0
SET USERPROFILE=%CURRENTDIRECTORY%Users\LlxprtCli
SET APPDATA=%CURRENTDIRECTORY%Users\LlxprtCli\AppData\Roaming
IF NOT EXIST "%APPDATA%" MKDIR "%APPDATA%" >NUL

ECHO .
ECHO To launch Llxprt Cli enter: Llxprt
