@ECHO OFF
SET CURRENTDIR=%~dp0
SET USERPROFILE=%CURRENTDIR%Users\LlxprtCli
SET APPDATA=%CURRENTDIR%Users\LlxprtCli\AppData\Roaming
SET LOCALAPPDATA=%CURRENTDIR%Users\LlxprtCli\AppData\Local
IF NOT EXIST "%APPDATA%" MKDIR "%APPDATA%" >NUL
IF NOT EXIST "%LOCALAPPDATA%" MKDIR "%LOCALAPPDATA%" >NUL

ECHO .
ECHO To launch Llxprt Cli enter: Llxprt
