@ECHO OFF
SET CURRENTDIRECTORY=%~dp0
SET USERPROFILE=%CURRENTDIRECTORY%Users\GeminiCli
SET APPDATA=%CURRENTDIRECTORY%Users\GeminiCli\AppData\Roaming
SET LOCALAPPDATA=%CURRENTDIR%Users\GeminiCli\AppData\Local
IF NOT EXIST "%APPDATA%" MKDIR "%APPDATA%" >NUL
IF NOT EXIST "%LOCALAPPDATA%" MKDIR "%LOCALAPPDATA%" >NUL

ECHO .
ECHO To launch Gemini Cli enter: Gemini
