@ECHO OFF
SET CURRENTDIRECTORY=%~dp0
SET USERPROFILE=%CURRENTDIRECTORY%Users\GeminiCli
SET APPDATA=%CURRENTDIRECTORY%Users\GeminiCli\AppData\Roaming
IF NOT EXIST "%APPDATA%" MKDIR "%APPDATA%" >NUL

ECHO .
ECHO To launch Gemini Cli enter: Gemini
