@ECHO OFF
SET CURRENTDIRECTORY=%~dp0
SET USERPROFILE=%CURRENTDIRECTORY%Users\Antigravity
SET APPDATA=%CURRENTDIRECTORY%Users\Antigravity\AppData\Roaming
SET LOCALAPPDATA=%CURRENTDIRECTORY%Users\Antigravity\AppData\Local
SET PATH=%USERPROFILE%\AppData\Local\Programs\Antigravity IDE;%PATH%
IF NOT EXIST "%APPDATA%" MKDIR "%APPDATA%" >NUL
IF NOT EXIST "%LOCALAPPDATA%" MKDIR "%LOCALAPPDATA%" >NUL

ECHO.
ECHO Start Antigravity IDE by: "Antigravity IDE" .
