@ECHO OFF
SET CURRENTDIRECTORY=%~dp0
SET USERPROFILE=%CURRENTDIRECTORY%Users\Antigravity
SET APPDATA=%CURRENTDIRECTORY%Users\Antigravity\AppData\Roaming
SET LOCALAPPDATA=%CURRENTDIRECTORY%Users\Antigravity\AppData\Local
SET PATH=%USERPROFILE%AppData\Local\Programs\Antigravity;%PATH%
IF NOT EXIST "%APPDATA%" MKDIR "%APPDATA%" >NUL
IF NOT EXIST "%LOCALAPPDATA%" MKDIR "%LOCALAPPDATA%" >NUL

SET PATH=%LOCALAPPDATA%\Programs\Antigravity;%PATH%

ECHO.
ECHO Start Antigravity by: Antigravity .
