@ECHO OFF
SET CURRENTDIRECTORY=%~dp0
SET PATH=%CD:~0,2%\VSCode;%PATH%
SET USERPROFILE=%CURRENTDIRECTORY%Users\Codex
SET APPDATA=%CURRENTDIRECTORY%Users\Codex\AppData\Roaming
SET LOCALAPPDATA=%CURRENTDIRECTORY%Users\Codex\AppData\Local
IF NOT EXIST %APPDATA% MKDIR %APPDATA% >NUL
IF NOT EXIST "%LOCALAPPDATA%" MKDIR "%LOCALAPPDATA%" >NUL

ECHO.
ECHO Start Codex by executing: -> Todo